authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='create'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import path

from . import views

# recipes:recipe ou recipes:home
app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
    path('recipes/category/<int:category_id>/',
         views.category, name='category'),
    path('recipes/search/',
         views.search, name='search'),
]

authors/models.py
from django.db import models

# Create your models here.

recipes/models.py
from turtle import title
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    serving_units = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None,
    )
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')

    def __str__(self):
        return self.title

authors/forms.py
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User


def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attr[attr_name] = f'{existing_attr} {attr_new_val}'.strip()


def add_placeholder(field, placeholder_val):
    add_attr(field, 'placeholder', placeholder_val)


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Type your username')
        add_placeholder(self.fields['email'], 'Type your e-mail')
        add_placeholder(self.fields['first_name'],
                        'Type your first name Ex.: John')
        add_placeholder(self.fields['last_name'],
                        'Type your last name Ex.: Doe')
        add_attr(self.fields['username'], 'css', 'a-css-class')

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Type your password'
        }),
        error_messages={
            'required': 'Password must not be empty'
        },
        help_text=(
            'Password must have at least one uppercase letter, '
            'one lowercase letter and one number. The length should be '
            'at least 8'
        )
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat your password'
        }),
        error_messages={
            'required': 'Password must not be empty'
        },
        help_text=(
            'Password must have at least one uppercase letter, '
            'one lowercase letter and one number. The length should be '
            'at least 8'
        )
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

        labels = {
            'first_name': 'First name',
            'last_name': 'Last name',
            'username': 'Username',
            'email': 'Email',
            'password': 'Password',
        }

        help_texts = {
            'email': 'The e-mail must be valid'
        }

        error_messages = {
            'username': {
                'required': 'This field must not be empty.',
            }
        }

        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Type your username',
                'class': 'input text-input'
            }),
            'password': forms.PasswordInput(attrs={
                'placeholder': 'Type your password'
            })
        }

    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError(
                'Password and password2 must be equal',
                code='invalid'
            )
            raise ValidationError({
                'password': password_confirmation_error,
                'password2': [password_confirmation_error,],
            })

authors/views.py
from django.http import Http404
from django.shortcuts import redirect, render

from authors.forms import RegisterForm

# Create your views here.


def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)
    return render(request, 'authors/pages/register_view.html', {
        'form': form,
    })


def register_create(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    return redirect('authors:register')

recipes/views.py
import os
from django.http import Http404
from django.db.models import Q
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.contrib import messages

from utils.recipes.pagination import make_pagination
from .models import Recipe

PER_PAGE = int(os.environ.get('PER_PAGE', 3))

# Create your views here.


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    page_object, pagination_range = make_pagination(
        request, recipes, PER_PAGE)

    messages.error(request, 'Epa, você foi pesquisar algo que eu vi.')
    messages.success(request, 'Epa, você foi pesquisar algo que eu vi.')
    messages.info(request, 'Epa, você foi pesquisar algo que eu vi.')

    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_object,
        'pagination_range': pagination_range
    })


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(category__id=category_id, is_published=True,).order_by('-id'))

    page_object, pagination_range = make_pagination(
        request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/category.html', context={
        'recipes': page_object,
        'pagination_range': pagination_range,
        'title': f'{recipes[0].category.name} - Category | '  # type: ignore
    })


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })


def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(Q(title__icontains=search_term) |
          Q(description__icontains=search_term)),
        is_published=True
    ).order_by('-id')

    page_object, pagination_range = make_pagination(
        request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'Search for "{search_term}"',
        'search_term': search_term,
        'recipes': page_object,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}',
    })

authors/templates/authors/pages/register_view.html
{% extends "global/base.html" %}

{% block title %}Register |{% endblock title %}

{% block receita %}
    <div class="main-content center container">
        <h2>Register {{ request.session.number }}</h2>
    </div>
    <div class="main-content center container">
        <form action="{% url 'authors:create' %}" method="POST">
            {% csrf_token %}
            <div class="form-content form-content-grid">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}

                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}

                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>
            <div class="form-content form-content-grid">
                <div class="form-group">
                  <button type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>
{% endblock receita %}

recipes/templates/home.html
<!DOCTYPE html>
<html lang="pt_br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recipes</title>
</head>

<body>
    <h1>Recipes</h1>
</body>

</html>

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

<title>{% block title %}{{ title }}{% endblock title %}</title>

{% block receita %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
    {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock receita %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block receita %}

{% include 'recipes/partials/messages.html' %}

<div class="main-content main-content-list container">
{% for recipe in recipes %}
    {% include 'recipes/partials/recipe.html' %}
{% empty %}
    <div class="center m-y">
        <h1 class="center">No recipes have been found!</h1>
    </div>
{% endfor %}
</div>
{% endblock receita %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

<title>{% block title %}{{ recipe.title }} |{% endblock title %}</title>

{% block receita %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock receita %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

<title>{% block title %}{{ page_title }} |{% endblock title %}</title>

{% block receita %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% empty %}
        <h1 class="center">No recipes have been found!</h1>
    {% endfor %}
</div>
{% endblock receita %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://github.com/GabrielAndreiJunges" target="_blank" rel="noreferrer noopener">By Gabriel Andrei
            Junges</a>
    </div>
    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'global/css/global-styles.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url "recipes:home" %}">
                <i class="fas fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/messages.html
{% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
        <div class="message {{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}

recipes/templates/recipes/partials/pagination.html
{% if recipes.has_other_pages %}
    <div class="container pagination">
        <div class="pagination-content">
            {% if pagination_range.first_page_is_out_of_range %}
                <a href="?page=1{{ additional_url_query }}" class="page-link page-item">1</a>
                <span class="page-items">...</span>
                
            {% endif %}
            {% for page in pagination_range.pagination %}
                {% if pagination_range.current_page == page %}
                    <a href="?page={{ page }}{{ additional_url_query }}" class="page-link page-item page-current">{{ page }}</a>
                    {% else %}
                    <a href="?page={{ page }}{{ additional_url_query }}" class="page-link page-item">{{ page }}</a>
                {% endif %}
            {% endfor %}

            {% if pagination_range.last_page_is_out_of_range %}
                <span class="page-item">...</span>
                <a href="?page={{ pagination_range.total_pages}}{{ additional_url_query }}" class="page-link page-item">{{ pagination_range.total_pages}}</a>
            {% endif %}
        </div>
    </div>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            {% if not is_detail_page %}
                <a href="{% url "recipes:recipe" recipe.id %}">
                    <img src="{{ recipe.cover.url }}" alt="Temporário">
                </a>
            {% else %}
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            {% endif %}
        </div>
    {% endif %}
    <div class="recipe-title-container">
        {% if not is_detail_page %}
            <a href="{% url "recipes:recipe" recipe.id %}">
                <h2 class="recipe-title">{{ recipe.title }}.</h2>
            </a>
        {% else %}
            <h2 class="recipe-title">{{ recipe.title }}.</h2>
        {% endif %}
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>

            {% if recipe.author.first_name %}
            {{ recipe.author.first_name }} {{ recipe.author.first_name }}
            {% else %}
            {{ recipe.author.username }}
            {% endif %}

        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>

            {{ recipe.created_at|date:"d/m/Y" }}

        </span>

        {% if recipe.category is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
        {% endif %}
        
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.serving_units }}
            </div>
        </div>
    </div>
    {% if not is_detail_page == True %}
    <footer class="recipe-footer">
        <a href="{% url "recipes:recipe" recipe.id %}" class="recipe-read-more button button-dark button-full-width">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% else %}
    <div class="preparation-steps">
        {% if preparation_steps_is_html == True %}
            <p>{{ recipe.preparation_steps|safe }}</p>
        {% endif %}
            <p>{{ recipe.preparation_steps|linebreaksbr }}</p>
    </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url "recipes:search" %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>